name: severfire
favicon: null
layout_spectrum: 0.39507
typography_spectrum: 0.24393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0000'
    - '#b20000'
    - '#ea0001'
    - '#460000'
    - '#720000'
  brandStrength: 0.625
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
